name: images
on:
  push:
    branches:
      - k8s
env:
  CI_PROJECT_PATH: ${{ github.repository }}
jobs:
  build:
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          for target in default nginx; do
            nix build -L .#dockerImages.x86_64-linux.$target --extra-experimental-features 'nix-command flakes'
            skopeo copy --insecure-policy docker-archive://$(readlink -f ./result) docker://ghcr.io/$CI_PROJECT_PATH/$target:latest
          done

